name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "dev" ]

env:
  CI_SEMANTIC_RELEASE_PATH: "./semantic_release_modules"
  CI_SEMANTIC_RELEASE_PLUGINS: "@semantic-release/changelog @semantic-release/exec @semantic-release/git @semantic-release/github"

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repository
        uses: actions/checkout@v4
      - name: Install Node JS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Create directory
        run: mkdir -p $CI_SEMANTIC_RELEASE_PATH
      - name: Install semantic-release
        run: npm install semantic-release $CI_SEMANTIC_RELEASE_PLUGINS --prefix $CI_SEMANTIC_RELEASE_PATH
      - name: Create version tag
        run: npx --prefix $CI_SEMANTIC_RELEASE_PATH semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CI_COMMIT_BRANCH: ${{ github.ref }}

  cleanup:
    runs-on: ubuntu-latest
    needs: create_tag
    steps:
      - name: Cleaning the directory
        run: rm -rf ./*